### 1900-unit mLSTM

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import sys
import numpy as np
sys.path.append('/Users/aniton/Documents/GitHub/UniRep')
tf.random.set_random_seed(42)
np.random.seed(42)
!aws s3 sync --no-sign-request --quiet s3://unirep-public/1900_weights/ 1900_weights/
from unirep import babbler1900 as babbler
MODEL_WEIGHT_PATH = "./1900_weights"

Instructions for updating:
non-resource variables are not supported in the long term


In [8]:
from tf_slim.layers import layers as _layers
batch_size = 12
b = babbler(batch_size=batch_size, model_path=MODEL_WEIGHT_PATH)

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
dim is deprecated, use axis instead
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
Use `tf.random.categorical` instead.


/usr/local/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1719: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '


### 5-hydroxytryptamine receptor 7

In [9]:
seq = "MMDVNSSGRPDLYGHLRSFLLPEVGRGLPDLSPDGGADPVAGSWAPHLLSEVTASPAPTWDAPPDNASGCGEQINYGRVEKVVIGSILTLITLLTIAGNCLVVISVCFVKKLRQPSNYLIVSLALADLSVAVAVMPFVSVTDLIGGKWIFGHFFCNVFIAMDVMCCTASIMTLCVISIDRYLGITRPLTYPVRQNGKCMAKMILSVWLLSASITLPPLFGWAQNVNDDKVCLISQDFGYTIYSTAVAFYIPMSVMLFMYYQIYKAARKSAAKHKFPGFPRVEPDSVIALNGIVKLQKEVEECANLSRLLKHERKNISIFKREQKAATTLGIIVGAFTVCWLPFFLLSTARPFICGTSCSCIPLWVERTFLWLGYANSLINPFIYAFFNRDLRTTYRSLLQCQYRNINRKLSAAGMHEALKLAERPERPEFVLRACTRRVLLRPEKRPPVSVWVLQSPDHHNWLADKMLTTVEKKVMIHD"

#### average hidden representation

In [12]:
a = b.get_rep(seq)

In [13]:
a[0]

array([ 0.06724703, -0.0280663 ,  0.04971798, ...,  0.0425435 ,
        0.01492667, -0.04463214], dtype=float32)

#### final hidden representation

In [14]:
a[1]

array([ 0.00021911, -0.0279364 ,  0.03211641, ...,  0.03563059,
        0.03723566,  0.02737938], dtype=float32)

####  final cell representation

In [15]:
a[2]

array([ 4.509942  , -3.30547   ,  4.23504   , ...,  2.6672964 ,
        3.543985  ,  0.81329435], dtype=float32)

### 64-unit mLSTM

In [3]:
tf.random.set_random_seed(42)
np.random.seed(42)
!aws s3 sync --no-sign-request --quiet s3://unirep-public/64_weights/ 64_weights/
from unirep import babbler64 as babbler
MODEL_WEIGHT_PATH = "./64_weights"

In [4]:
batch_size = 12
b = babbler(batch_size=batch_size, model_path=MODEL_WEIGHT_PATH)

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
dim is deprecated, use axis instead
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
Use `tf.random.categorical` instead.


/usr/local/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1719: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '


In [5]:
seq = "MMDVNSSGRPDLYGHLRSFLLPEVGRGLPDLSPDGGADPVAGSWAPHLLSEVTASPAPTWDAPPDNASGCGEQINYGRVEKVVIGSILTLITLLTIAGNCLVVISVCFVKKLRQPSNYLIVSLALADLSVAVAVMPFVSVTDLIGGKWIFGHFFCNVFIAMDVMCCTASIMTLCVISIDRYLGITRPLTYPVRQNGKCMAKMILSVWLLSASITLPPLFGWAQNVNDDKVCLISQDFGYTIYSTAVAFYIPMSVMLFMYYQIYKAARKSAAKHKFPGFPRVEPDSVIALNGIVKLQKEVEECANLSRLLKHERKNISIFKREQKAATTLGIIVGAFTVCWLPFFLLSTARPFICGTSCSCIPLWVERTFLWLGYANSLINPFIYAFFNRDLRTTYRSLLQCQYRNINRKLSAAGMHEALKLAERPERPEFVLRACTRRVLLRPEKRPPVSVWVLQSPDHHNWLADKMLTTVEKKVMIHD"

In [6]:
a = b.get_rep(seq)

#### average hidden, final hidden, final cell representation arrays

In [7]:
print(a)

(array([-0.02442052,  0.12668233,  0.05974412, -0.96180606, -0.01348389,
       -0.2072217 ,  0.11382031,  0.14564557,  0.45236623, -0.07579868,
        0.15168576,  0.15382348, -0.00178124,  0.12680867, -0.04980928,
       -0.07084481, -0.9031778 ,  0.03589629,  0.14066233, -0.54970723,
       -0.08650241,  0.29881725, -0.32411703, -0.21963464,  0.14390944,
       -0.05468214, -0.05563748,  0.06209938,  0.32786408, -0.43265256,
        0.10956056,  0.37968376,  0.2716848 , -0.0917405 ,  0.7453777 ,
        0.11836982, -0.34010586,  0.07253375,  0.05995105, -0.1473391 ,
        0.02390106,  0.16314784, -0.00480597,  0.12641585, -0.18716659,
        0.08808956, -0.82002044, -0.22481933,  0.09638377,  0.2260205 ,
        0.26296222,  0.03258057, -0.00970771, -0.10038885,  0.14187522,
        0.01684602,  0.08079701, -0.01887866, -0.08594517,  0.26949283,
       -0.07932065, -0.03368478,  0.46189913, -0.03301748], dtype=float32), array([-0.0284293 ,  0.09124698, -0.10763494, -0.98538315, 