### 1900-unit mLSTM

In [1]:
USE_FULL_1900_DIM_MODEL = True 

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import sys
import numpy as np
sys.path.append('/Users/aniton/Documents/GitHub/UniRep')
# Set seeds
tf.random.set_random_seed(42)
np.random.seed(42)


    # Sync relevant weight files
!aws s3 sync --no-sign-request --quiet s3://unirep-public/1900_weights/ 1900_weights/
    
    # Import the mLSTM babbler model
from unirep import babbler1900 as babbler
    
    # Where model weights are stored.
MODEL_WEIGHT_PATH = "./1900_weights"

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
from tf_slim.layers import layers as _layers
batch_size = 12
b = babbler(batch_size=batch_size, model_path=MODEL_WEIGHT_PATH)

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
dim is deprecated, use axis instead
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
Use `tf.random.categorical` instead.


/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1719: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '


### 5-hydroxytryptamine receptor 7

In [4]:
seq = "MMDVNSSGRPDLYGHLRSFLLPEVGRGLPDLSPDGGADPVAGSWAPHLLSEVTASPAPTWDAPPDNASGCGEQINYGRVEKVVIGSILTLITLLTIAGNCLVVISVCFVKKLRQPSNYLIVSLALADLSVAVAVMPFVSVTDLIGGKWIFGHFFCNVFIAMDVMCCTASIMTLCVISIDRYLGITRPLTYPVRQNGKCMAKMILSVWLLSASITLPPLFGWAQNVNDDKVCLISQDFGYTIYSTAVAFYIPMSVMLFMYYQIYKAARKSAAKHKFPGFPRVEPDSVIALNGIVKLQKEVEECANLSRLLKHERKNISIFKREQKAATTLGIIVGAFTVCWLPFFLLSTARPFICGTSCSCIPLWVERTFLWLGYANSLINPFIYAFFNRDLRTTYRSLLQCQYRNINRKLSAAGMHEALKLAERPERPEFVLRACTRRVLLRPEKRPPVSVWVLQSPDHHNWLADKMLTTVEKKVMIHD"

#### average hidden representation

In [5]:
b.get_rep(seq)[0]

array([ 0.06724703, -0.0280663 ,  0.04971798, ...,  0.0425435 ,
        0.01492667, -0.04463214], dtype=float32)

#### final hidden representation

In [6]:
b.get_rep(seq)[1]

array([ 0.00021911, -0.0279364 ,  0.03211641, ...,  0.03563059,
        0.03723566,  0.02737938], dtype=float32)

####  final cell representation

In [7]:
b.get_rep(seq)[2]

array([ 4.509942  , -3.30547   ,  4.23504   , ...,  2.6672964 ,
        3.543985  ,  0.81329435], dtype=float32)

### 64-unit mLSTM

In [1]:
USE_FULL_64_DIM_MODEL = True 

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import sys
import numpy as np
sys.path.append('/Users/aniton/Documents/GitHub/UniRep')
# Set seeds
tf.random.set_random_seed(42)
np.random.seed(42)

# Sync relevant weight files
!aws s3 sync --no-sign-request --quiet s3://unirep-public/64_weights/ 64_weights/
    
    # Import the mLSTM babbler model
from unirep import babbler64 as babbler
    
    # Where model weights are stored.
MODEL_WEIGHT_PATH = "./64_weights"

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
from tf_slim.layers import layers as _layers
batch_size = 12
b = babbler(batch_size=batch_size, model_path=MODEL_WEIGHT_PATH)

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
dim is deprecated, use axis instead
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
Use `tf.random.categorical` instead.


/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1719: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '


In [4]:
seq = "MMDVNSSGRPDLYGHLRSFLLPEVGRGLPDLSPDGGADPVAGSWAPHLLSEVTASPAPTWDAPPDNASGCGEQINYGRVEKVVIGSILTLITLLTIAGNCLVVISVCFVKKLRQPSNYLIVSLALADLSVAVAVMPFVSVTDLIGGKWIFGHFFCNVFIAMDVMCCTASIMTLCVISIDRYLGITRPLTYPVRQNGKCMAKMILSVWLLSASITLPPLFGWAQNVNDDKVCLISQDFGYTIYSTAVAFYIPMSVMLFMYYQIYKAARKSAAKHKFPGFPRVEPDSVIALNGIVKLQKEVEECANLSRLLKHERKNISIFKREQKAATTLGIIVGAFTVCWLPFFLLSTARPFICGTSCSCIPLWVERTFLWLGYANSLINPFIYAFFNRDLRTTYRSLLQCQYRNINRKLSAAGMHEALKLAERPERPEFVLRACTRRVLLRPEKRPPVSVWVLQSPDHHNWLADKMLTTVEKKVMIHD"

In [6]:
a = b.get_rep(seq)

#### average hidden, final hidden, final cell representation arrays

In [7]:
print(a)

(array([-0.02442052,  0.12668233,  0.05974412, -0.96180606, -0.01348389,
       -0.2072217 ,  0.11382031,  0.14564557,  0.45236623, -0.07579868,
        0.15168576,  0.15382348, -0.00178124,  0.12680867, -0.04980928,
       -0.07084481, -0.9031778 ,  0.03589629,  0.14066233, -0.54970723,
       -0.08650241,  0.29881725, -0.32411703, -0.21963464,  0.14390944,
       -0.05468214, -0.05563748,  0.06209938,  0.32786408, -0.43265256,
        0.10956056,  0.37968376,  0.2716848 , -0.0917405 ,  0.7453777 ,
        0.11836982, -0.34010586,  0.07253375,  0.05995105, -0.1473391 ,
        0.02390106,  0.16314784, -0.00480597,  0.12641585, -0.18716659,
        0.08808956, -0.82002044, -0.22481933,  0.09638377,  0.2260205 ,
        0.26296222,  0.03258057, -0.00970771, -0.10038885,  0.14187522,
        0.01684602,  0.08079701, -0.01887866, -0.08594517,  0.26949283,
       -0.07932065, -0.03368478,  0.46189913, -0.03301748], dtype=float32), array([-0.0284293 ,  0.09124698, -0.10763494, -0.98538315, 

In [10]:
import numpy as np
import pandas as pd
meta = pd.read_csv("/Users/aniton/Documents/iMolecule/data/meta.csv")
meta.columns =["id", "seq", "description", "name", "organism"]
meta

id                                                seq  \
0  sp|O94910|AGRL1_HUMAN  MARLAAVLWNLCVTAVLVTSATQGLSRAGLPFGLMRRELACEGYPI...   
1  sp|Q80TR1|AGRL1_MOUSE  MARLAAALWSLCVTTVLVTSATQGLSRAGLPFGLMRRELACEGYPI...   
2  sp|P28222|5HT1B_HUMAN  MEEPGAQCAPPPPAGSETWVPQANLSSAPSQNCSAKDYIYQDSISL...   
3  sp|P79250|5HT1B_CANLF  MEAAGAPCAPPPPAGSQTGAPPANLSSAPHNCSAEGYIYQDSVALP...   
4  sp|P28334|5HT1B_MOUSE  MEEQGIQCAPPPPAASQTGVPLTNLSHNCSADGYIYQDSIALPWKV...   
5  sp|P34969|5HT7R_HUMAN  MMDVNSSGRPDLYGHLRSFLLPEVGRGLPDLSPDGGADPVAGSWAP...   
6  sp|P32304|5HT7R_MOUSE  MMDVNSSGRPDLYGHLRSLILPEVGRRLQDLSPDGGAHSVVSSWMP...   
7  sp|Q9HBW9|AGRL4_HUMAN  MKRLPLLVVFSTLLNCSYTQNCTKTPCLPNAKCEIRNGIEACYCNM...   
8  sp|Q923X1|AGRL4_MOUSE  MRLLPLLVGFSTLLNCSYTQNCSKTTCLPNAKCEVHNGVEACFCSQ...   
9  sp|Q7SY09|AGRL4_DANRE  MKLLLFAAWFSSLLDPCRFLDICQSCHPNADCDDICKCRTGYTGNG...   

                                         description                   name  \
0  sp|O94910|AGRL1_HUMAN Adhesion G protein-coupl...  sp|O94910|AGRL1_HUMAN   
1  sp|Q80TR1|AGRL1_MOUSE Adhesion G protein-coupl...  sp|Q80TR1|AGRL1_MOUSE   
2  sp|P28222|5HT1B_HUMAN 5-hydroxytryptamine rece...  sp|P28222|5HT1B_HUMAN   
3  sp|P79250|5HT1B_CANLF 5-hydroxytryptamine rece...  sp|P79250|5HT1B_CANLF   
4  sp|P28334|5HT1B_MOUSE 5-hydroxytryptamine rece...  sp|P28334|5HT1B_MOUSE   
5  sp|P34969|5HT7R_HUMAN 5-hydroxytryptamine rece...  sp|P34969|5HT7R_HUMAN   
6  sp|P32304|5HT7R_MOUSE 5-hydroxytryptamine rece...  sp|P32304|5HT7R_MOUSE   
7  sp|Q9HBW9|AGRL4_HUMAN Adhesion G protein-coupl...  sp|Q9HBW9|AGRL4_HUMAN   
8  sp|Q923X1|AGRL4_MOUSE Adhesion G protein-coupl...  sp|Q923X1|AGRL4_MOUSE   
9  sp|Q7SY09|AGRL4_DANRE Adhesion G protein-coupl...  sp|Q7SY09|AGRL4_DANRE   

    organism  
0      human  
1      mouse  
2      human  
3        dog  
4      mouse  
5      human  
6      mouse  
7      human  
8      mouse  
9  zebrafish

In [11]:
reps = np.memmap("/Users/aniton/Documents/iMolecule/data/avg_hidden_full_53.memnpy",
                     mode="r",
                     dtype=np.float32,
                     shape=(10, 1900)
                     )

In [12]:
reps

memmap([[ 0.00409179, -0.02905684,  0.05819068, ..., -0.00640377,
          0.05548698,  0.03035289],
        [ 0.0080851 , -0.00502201,  0.04631828, ..., -0.00594639,
          0.09829481, -0.00456978],
        [ 0.00619606,  0.12493809,  0.13175243, ...,  0.08588191,
         -0.01561721,  0.07642487],
        ...,
        [ 0.00378827, -0.03524483,  0.04061274, ...,  0.03318325,
          0.02388165,  0.06336185],
        [ 0.0031024 , -0.00694551,  0.07315227, ...,  0.04098549,
         -0.13327664,  0.24890031],
        [ 0.00289314, -0.02245093,  0.04616727, ...,  0.02191218,
          0.08017933, -0.00907807]], dtype=float32)