### 1900-unit mLSTM

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import sys
import numpy as np
sys.path.append('/Users/aniton/Documents/GitHub/UniRep')
tf.random.set_random_seed(42)
np.random.seed(42)
!aws s3 sync --no-sign-request --quiet s3://unirep-public/1900_weights/ 1900_weights/
from unirep import babbler1900 as babbler
MODEL_WEIGHT_PATH = "./1900_weights"

Instructions for updating:
non-resource variables are not supported in the long term


In [8]:
from tf_slim.layers import layers as _layers
batch_size = 12
b = babbler(batch_size=batch_size, model_path=MODEL_WEIGHT_PATH)

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
dim is deprecated, use axis instead
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
Use `tf.random.categorical` instead.


/usr/local/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1719: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '


### 5-hydroxytryptamine receptor 7

In [9]:
seq = "MMDVNSSGRPDLYGHLRSFLLPEVGRGLPDLSPDGGADPVAGSWAPHLLSEVTASPAPTWDAPPDNASGCGEQINYGRVEKVVIGSILTLITLLTIAGNCLVVISVCFVKKLRQPSNYLIVSLALADLSVAVAVMPFVSVTDLIGGKWIFGHFFCNVFIAMDVMCCTASIMTLCVISIDRYLGITRPLTYPVRQNGKCMAKMILSVWLLSASITLPPLFGWAQNVNDDKVCLISQDFGYTIYSTAVAFYIPMSVMLFMYYQIYKAARKSAAKHKFPGFPRVEPDSVIALNGIVKLQKEVEECANLSRLLKHERKNISIFKREQKAATTLGIIVGAFTVCWLPFFLLSTARPFICGTSCSCIPLWVERTFLWLGYANSLINPFIYAFFNRDLRTTYRSLLQCQYRNINRKLSAAGMHEALKLAERPERPEFVLRACTRRVLLRPEKRPPVSVWVLQSPDHHNWLADKMLTTVEKKVMIHD"

#### average hidden representation

In [12]:
a = b.get_rep(seq)

In [13]:
a[0]

array([ 0.06724703, -0.0280663 ,  0.04971798, ...,  0.0425435 ,
        0.01492667, -0.04463214], dtype=float32)

#### final hidden representation

In [14]:
a[1]

array([ 0.00021911, -0.0279364 ,  0.03211641, ...,  0.03563059,
        0.03723566,  0.02737938], dtype=float32)

####  final cell representation

In [15]:
a[2]

array([ 4.509942  , -3.30547   ,  4.23504   , ...,  2.6672964 ,
        3.543985  ,  0.81329435], dtype=float32)

### 64-unit mLSTM

In [3]:
tf.random.set_random_seed(42)
np.random.seed(42)
!aws s3 sync --no-sign-request --quiet s3://unirep-public/64_weights/ 64_weights/
from unirep import babbler64 as babbler
MODEL_WEIGHT_PATH = "./64_weights"

In [4]:
batch_size = 12
b = babbler(batch_size=batch_size, model_path=MODEL_WEIGHT_PATH)

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
dim is deprecated, use axis instead
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
Use `tf.random.categorical` instead.


/usr/local/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1719: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '


In [5]:
seq = "MMDVNSSGRPDLYGHLRSFLLPEVGRGLPDLSPDGGADPVAGSWAPHLLSEVTASPAPTWDAPPDNASGCGEQINYGRVEKVVIGSILTLITLLTIAGNCLVVISVCFVKKLRQPSNYLIVSLALADLSVAVAVMPFVSVTDLIGGKWIFGHFFCNVFIAMDVMCCTASIMTLCVISIDRYLGITRPLTYPVRQNGKCMAKMILSVWLLSASITLPPLFGWAQNVNDDKVCLISQDFGYTIYSTAVAFYIPMSVMLFMYYQIYKAARKSAAKHKFPGFPRVEPDSVIALNGIVKLQKEVEECANLSRLLKHERKNISIFKREQKAATTLGIIVGAFTVCWLPFFLLSTARPFICGTSCSCIPLWVERTFLWLGYANSLINPFIYAFFNRDLRTTYRSLLQCQYRNINRKLSAAGMHEALKLAERPERPEFVLRACTRRVLLRPEKRPPVSVWVLQSPDHHNWLADKMLTTVEKKVMIHD"

In [6]:
a = b.get_rep(seq)

#### average hidden, final hidden, final cell representation arrays

In [7]:
print(a)

(array([-0.02442052,  0.12668233,  0.05974412, -0.96180606, -0.01348389,
       -0.2072217 ,  0.11382031,  0.14564557,  0.45236623, -0.07579868,
        0.15168576,  0.15382348, -0.00178124,  0.12680867, -0.04980928,
       -0.07084481, -0.9031778 ,  0.03589629,  0.14066233, -0.54970723,
       -0.08650241,  0.29881725, -0.32411703, -0.21963464,  0.14390944,
       -0.05468214, -0.05563748,  0.06209938,  0.32786408, -0.43265256,
        0.10956056,  0.37968376,  0.2716848 , -0.0917405 ,  0.7453777 ,
        0.11836982, -0.34010586,  0.07253375,  0.05995105, -0.1473391 ,
        0.02390106,  0.16314784, -0.00480597,  0.12641585, -0.18716659,
        0.08808956, -0.82002044, -0.22481933,  0.09638377,  0.2260205 ,
        0.26296222,  0.03258057, -0.00970771, -0.10038885,  0.14187522,
        0.01684602,  0.08079701, -0.01887866, -0.08594517,  0.26949283,
       -0.07932065, -0.03368478,  0.46189913, -0.03301748], dtype=float32), array([-0.0284293 ,  0.09124698, -0.10763494, -0.98538315, 

### Fingerprints

In [25]:
import pandas as pd
df = pd.read_csv('for5-HT7.csv', sep=';')
df = df.dropna(subset=['Smiles', 'Molecule ChEMBL ID']).drop_duplicates(subset=['Molecule ChEMBL ID'])

In [26]:
import  rdkit
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import Image
from rdkit.Chem import DataStructs

In [27]:
df['mol'] = df['Smiles'].apply(Chem.MolFromSmiles)
df = df.dropna(subset=['mol'])
df['HeavyAtomCount'] = df['mol'].apply(Descriptors.HeavyAtomCount)
df['HAccept'] = df['mol'].apply(Descriptors.NumHAcceptors)
df['HDonor'] = df['mol'].apply(Descriptors.NumHDonors)
df['Heteroatoms'] = df['mol'].apply(Descriptors.NumHeteroatoms)
df['RingCount'] = df['mol'].apply(Descriptors.RingCount)
df['SaturatedRings'] = df['mol'].apply(Descriptors.NumSaturatedRings)
df['AliphaticRings'] = df['mol'].apply(Descriptors.NumAliphaticRings)
df['AromaticRings'] = df['mol'].apply(Descriptors.NumAromaticRings)
df['Ipc'] = df['mol'].apply(Descriptors.Ipc)
df['HallKierAlpha'] = df['mol'].apply(Descriptors.HallKierAlpha)
df['NumValenceElectrons'] = df['mol'].apply(Descriptors.NumValenceElectrons)

In [28]:
df["ECFP6"] = df['mol'].apply(AllChem.GetMorganFingerprintAsBitVect, args=(3, 2048))

In [30]:
df.head(13)

Molecule ChEMBL ID Molecule Name  Molecule Max Phase  Molecular Weight  \
0         CHEMBL72008           NaN                   0            391.52   
1        CHEMBL428494           NaN                   0            390.53   
2         CHEMBL18840           NaN                   0            203.25   
3        CHEMBL281923           NaN                   0            291.39   
4        CHEMBL260551           NaN                   0            464.41   
5        CHEMBL152595           NaN                   0            400.59   
6         CHEMBL13816           NaN                   0            389.50   
7        CHEMBL268921           NaN                   0            361.49   
8        CHEMBL151858           NaN                   0            373.56   
9        CHEMBL239897           NaN                   0            435.49   
10        CHEMBL79587           NaN                   0            399.32   
11       CHEMBL267615           NaN                   0            246.35   
12       CHEMBL401541           NaN                   0            181.63   

    #RO5 Violations  AlogP Compound Key  \
0                 0   3.00          23n   
1                 0   3.60          23m   
2                 0   0.77         5-CT   
3                 0   3.66          82d   
4                 1   5.72          9f'   
5                 0   4.51           18   
6                 0   4.05            7   
7                 0   3.43            1   
8                 0   4.76           10   
9                 0   3.85            9   
10                1   6.05          30A   
11                0   2.84            8   
12                0   1.39            1   

                                               Smiles Standard Type  \
0        O=C1Nc2cccc3c2C1(CCCCN1CCN(c2ncccn2)CC1)CCC3            Ki   
1        O=C1Nc2cccc3c2C1(CCCCN1CCN(c2ccccn2)CC1)CCC3            Ki   
2                         NCCc1c[nH]c2ccc(C(N)=O)cc12            Ki   
3    CO[C@@]1(C)c2cccc3c2-c2c1ccc1c2[C@@H](C3)N(C)CC1            Ki   
4   CCC1(CCCCN2CCN(c3ccc(Cl)cc3)CC2)C(=O)Nc2cc(F)c...            Ki   
5   CC1CCN(CC[C@@H]2CCCCN2S(=O)(=O)c2cccc3ccccc23)CC1            Ki   
6   CN1C[C@H](CNC(=O)OCc2ccccc2)C[C@@H]2c3cccc4[nH...            Ki   
7          O=C1Nc2cccc3c2C1(CCN1CCN(c2ccccc2)CC1)CCC3            Ki   
8   CC([C@H](C)CCN1CCC[C@H](C)C1)S(=O)(=O)c1cccc2c...            Ki   
9   O=C1C2=C(CCCC2)C(=O)N1CCCCN1CCN(c2cccc(C(F)(F)...            Ki   
10    Cc1ccccc1[C@@H](Nc1ccc(Cl)cc1Cl)C(=O)CCc1ccncc1            Ki   
11                      CCc1[nH]c2ccc(OC)cc2c1CCN(C)C            Ki   
12                               NC1=Nc2cccc(Cl)c2CN1            Ki   

   Standard Relation  ...  HDonor Heteroatoms  RingCount SaturatedRings  \
0                '='  ...       1           6          5              1   
1                '='  ...       1           5          5              1   
2                '<'  ...       3           4          2              0   
3                '='  ...       0           2          5              0   
4                '='  ...       1           7          4              1   
5                '='  ...       0           5          4              2   
6                '='  ...       2           5          5              1   
7                '='  ...       1           4          5              1   
8                '='  ...       0           4          3              1   
9                '='  ...       0           8          4              1   
10               NaN  ...       1           5          3              0   
11               '='  ...       1           3          2              0   
12               '='  ...       2           4          2              0   

   AliphaticRings AromaticRings           Ipc  HallKierAlpha  \
0               3             2  8.827271e+06          -2.47   
1               3             2  8.827271e+06          -2.40   
2               0             2  3.765162e+03          -1.81   
3               3  